# Generated by Django 4.0.6 on 2022-11-16 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_local_promocion'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='direccion_local',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='local',
            name='nombre_local',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='promocion',
            name='descripcion_promo',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='promocion',
            name='fecha_fin',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='promocion',
            name='fecha_ini',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='promocion',
            name='id_local',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crud.local'),
        ),
        migrations.AddField(
            model_name='promocion',
            name='nombre_promo',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
