# Generated by Django 4.0.6 on 2022-11-16 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_local_direccion_local_local_nombre_local_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocion',
            name='fecha_ini',
            field=models.DateField(null=True),
        ),
    ]
