# Generated by Django 4.0.6 on 2022-11-16 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_alter_promocion_fecha_ini'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocion',
            name='fecha_ini',
            field=models.DateField(null=True, verbose_name='fecha inicio'),
        ),
    ]
