# Generated by Django 4.0.6 on 2022-11-16 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0009_metodo_pago_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='trabajador',
            fields=[
                ('rut_trabajador', models.CharField(max_length=10, null=True, primary_key=True, serialize=False, verbose_name='Rut')),
                ('nombre_trabajador', models.CharField(max_length=50, null=True, verbose_name='Nombre trabajador')),
                ('tipo_trabajador', models.CharField(max_length=50, null=True, verbose_name='Tipo trabajador')),
            ],
        ),
        migrations.CreateModel(
            name='pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(null=True)),
                ('estado', models.CharField(max_length=30, null=True)),
                ('calificacion', models.IntegerField()),
                ('id_local', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crud.local', verbose_name='Id local')),
                ('id_tipo_pago', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crud.metodo_pago', verbose_name='Metodo de pago')),
                ('rut_cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crud.cliente', verbose_name='Rut cliente')),
                ('rut_trabajador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crud.trabajador', verbose_name='Rut trabajador')),
            ],
        ),
        migrations.CreateModel(
            name='detalle_pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.ImageField(upload_to='')),
                ('id_pedido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crud.pedido')),
                ('id_producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crud.producto')),
            ],
        ),
    ]
