# Generated by Django 4.0.6 on 2022-11-16 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0010_trabajador_pedido_detalle_pedido'),
    ]

    operations = [
        migrations.DeleteModel(
            name='detalle_pedido',
        ),
    ]
