# Generated by Django 4.0.6 on 2022-11-16 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0011_delete_detalle_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocion',
            name='descripcion_promo',
            field=models.TextField(max_length=50, null=True, verbose_name='Descripcion'),
        ),
        migrations.CreateModel(
            name='detalle_pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('id_pedido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crud.pedido')),
                ('id_producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crud.producto')),
            ],
        ),
    ]
