# Generated by Django 4.0.6 on 2022-12-12 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0012_alter_promocion_descripcion_promo_detalle_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='id'),
        ),
    ]
