# Generated by Django 4.0.6 on 2022-12-12 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0013_alter_producto_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nom_producto',
            field=models.CharField(max_length=200, null=True, verbose_name='Nombre producto'),
        ),
    ]
