# Generated by Django 4.0.6 on 2022-12-12 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0014_alter_producto_nom_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='fecha',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
