# Generated by Django 4.0.6 on 2022-12-12 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0015_alter_pedido_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_pedido',
            name='precio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
